name: Deploy to Droplet
on:
  # push:
  #   branches:
  #     - main
  workflow_dispatch:
  
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Connect to Droplet
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USERNAME }}
          key: ${{ secrets.DROPLET_KEY }}
          port: 22
          script: |
            # Go to the http folder
            cd /var/www/http/
            
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            pnpm --help

            nvm use 20.11.1

            eval $(ssh-agent -s)
            ssh-add ~/.ssh/id_rsa
            
            git pull

            sudo systemctl stop svelteapp.service
            
            node -v
            pnpm -v
            pnpm i

#            pnpm run build
            
            sudo systemctl start svelteapp.service
